### PR TITLE
Modernise Autotools build system

### PR DESCRIPTION
**Pull request by SoapGentoo**
Hi @OlafvdSpek 
This is a general cleanup such that the build system is easier to use and we don't have to patch it in Gentoo.

* Remove Autotools cruft (`ltmain.sh` and friends) and add to .gitignore
* No need to add `INSTALL` and `COPYING` to the `doc_DATA` targets. These files shouldn't be installed, and there is no need to add them to `doc_DATA`, as Automake will still add them to the tarball.
* Use `AX_PTHREAD`, which is the modern replacement for `ACX_PTHREAD`.
* Do not override `$(docdir)`, which is a user flag and shouldn't be modified according to GNU conventions.
* Install html files into `$(htmldir)` and not `$(docdir)`.
* Only build tests when they are requested, that is, test targets should be prefixed with `check_` and not `noinst_`.
* Copy the `.cc` file to `.c` instead of using `$(LN_S)` which breaks `VPATH` (out-of-source builds).
* Rename `README_windows.txt` to `ReadMe_windows.txt` and install only when running on Windows/MinGW.

### CODE REVIEW

**Comment by OlafvdSpek** [comment]
Hi SoapGentoo,

Thanks a lot!

> Install the README_windows.txt only when running on Windows/MinGW.

The .zip is build on Linux and it should include this readme. Perhaps the .tar.gz should include it too in case the user downloads that one.

Was the autotools cruft not used at all?

**Comment by SoapGentoo** [comment]
@OlafvdSpek thanks for considering this PR
1. The `README_windows.txt` is in `dist_doc_DATA` protected by an `AM_CONDITIONAL`. That means it gets included in the tarball unconditionally, but installed only conditionally.
2. The Autotools cruft is absolutely necessary to work - it should just never be checked into the VCS. The VCS should only contain the absolute minimum number of files to produce the tarball (i.e. `configure.ac` and `Makefile.am`). All the Autotools cruft gets readded if you run `autoreconf -vif`, i.e., they contain no essential information. This problem actually runs deeper - The libtool version in the tree is 2.2.6b, this release is from November 2009 and over 7 years old. GNU Libtool is one of those monsters where you should always use the most recent version, as bugs do get fixed. For instance, in Gentoo we still struggle with a number of packages using an ancient version of Libtool that filters the `--as-needed` flag, which is crucial for minimizing overlinking (https://blog.flameeyes.eu/2011/06/gold-readiness-obstacle-4-libtool-part-1/)

I've also renamed `README_windows.txt` to `ReadMe_windows.txt` if that is ok with you. The reason is that we have a wildcard filter that installs all files matching `README*` (https://github.com/gentoo/gentoo/blob/master/eclass/eutils.eclass#L1798), independent of the build system. This would lead to installing that Windows ReadMe either how. Renaming makes it a bit easier for us if that's fine with you.

**Comment by OlafvdSpek** [comment]
I'm not sure about the rename, it's Gentoo-specific.. not entirely sure about .gitignore either.
Could we do one thing at a time, perhaps starting with unversioning the autotools cruft?
I agree it shouldn't be in the VCS, I already moved some auto-generated stuff but apparently not everything.

**Comment by SoapGentoo** [comment]
@OlafvdSpek Adding those to `.gitignore` is standard practice (see for instance https://github.com/systemd/systemd/blob/master/.gitignore). The Readme isn't that important, but this isn't purely a Gentoo problem - Debian, Funtoo and I think Mageia also have such hooks, so it would help them too.

Regarding making everything in one bloc, do you want me to split it up by commit or by PR?

**Comment by OlafvdSpek** [comment]
By PR, I think. I'm kinda new to Git. ;)

If it's easier for you I'm also fine with 'manually' making all changes myself.

**Comment by SoapGentoo** [comment]
@OlafvdSpek 
you don't have to do it manually, just tell me which logical/semantic changes you want grouped and I will do it.

**Comment by OlafvdSpek** [comment]
Let's do everything but the rename and .gitignore..

How do I build your branch? I tried but can't figure it out.

```
olaf@wheezy:~/ctemplate$ ./autogen.sh 
+ rm -rf autom4te.cache
+ aclocal --force -I m4
+ autoconf -f -W all,no-obsolete
configure.ac:44: error: possibly undefined macro: AC_DISABLE_FAST_INSTALL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:47: error: possibly undefined macro: AC_ENABLE_FAST_INSTALL
```

**Comment by SoapGentoo** [comment]
@OlafvdSpek I've fixed that. You will have to probably delete the tree and reclone, as I rebased and force pushed.

**Comment by OlafvdSpek** [comment]
Thx, but..

```
olaf@wheezy:~/ctemplate$ ./autogen.sh 
+ rm -rf autom4te.cache
+ aclocal --force -I m4
+ autoconf -f -W all,no-obsolete
+ autoheader -f -W all
+ automake -a -c -f -W all
Makefile.am:69: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:69:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:69:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:69:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:69:   its definition is in aclocal's search path.
```

**Comment by SoapGentoo** [comment]
@OlafvdSpek Try again. I use `autoreconf -vif` instead of the `autogen.sh` script. You were missing the `libtoolize` command, which is need now, as we removed the Libtool cruft.

**Comment by SoapGentoo** [comment]
@OlafvdSpek I've rebased on your changes and put `autoreconf` in `autogen.sh`, which is better and less troublesome than calling the autotools by themselves. Would you merge this?

**Comment by OlafvdSpek** [comment]
Can't m4/ax_pthread.m4 be auto-generated as well?

And is an unconditional disable-fast-install normal? 
TBH I've no idea what it does..

**Comment by SoapGentoo** [comment]
`m4/ax_pthread.m4` definitely cannot be removed, it contains the code for finding pthreads on different platforms, it is absolutely essential and the only way to portably use pthreads.

`disable-fast-install` has to do with relinking. If you use the binaries from the source tree when developing, then I would keep this, which causes a relinking in the install step but makes developing a slight bit easier. In practice, the speed gains from dropping it are negligible. Back 10 years ago it was needed on some broken MinGW systems. Drop it or leave it - it doesn't make a difference for distros. The one think you are not allowed to do, is change the default conditionally (like it was before, this breaks the macros as the instantiation code cannot be made runtime aware). Either enable or disable it globally for **all** platforms.

**Pull request merged**
