### PR TITLE
Solves C3083 error on msvc

### PR DESCRIPTION
**Pull request by atkawa7**
@OlafvdSpek Could you add this to help building on vcpkg

### CODE REVIEW

**Comment by OlafvdSpek** [comment]
The defines were there before but I can't reproduce this issue. On what compiler versions are you seeing this issue?

**Comment by atkawa7** [comment]
I was seeing the issue on visual studio. Thus the reason for this patch 

https://github.com/Microsoft/vcpkg/blob/master/ports/ctemplate/fix-msvc.patch

**Comment by OlafvdSpek** [comment]
What version?
I'd prefer to be able to reproduce it.

**Comment by atkawa7** [comment]
@OlafvdSpek  I don't remember exactly as now I am using both 2017 and 2015.

**Comment by atkawa7** [comment]
@OlafvdSpek  I think I was using this commit 44b7c5b918a08ad561c63e9d28beecb40c10ebca which you might have fixed

**Comment by OlafvdSpek** [comment]
Perhaps.

BTW, I'd like to get rid of the Python 2 dependency but I'm not entirely sure how it works. If I remove some Python related lines I don't get any Python related errors, just linker errors.

**Comment by atkawa7** [comment]
@OlafvdSpek I see. Just wondering. Are you able post the errors you are getting? I might be able able to help.

**Pull request closed without merging**
